### PR TITLE
Fix multiple help sidebars

### PR DESCRIPTION
**Pull request by smkdm**
Version 0.5.1 fixes Issue #7 Multiple Help Sidebars appearing

### CODE REVIEW

**Comment by bresche** [comment]
Thank you for your update and fix the help system. Can you fix the build? Some tests are broken.

**Comment by smkdm** [comment]
Hello Matthias,
my suggestion is to remove the one failing test - it uses Cuba internal methods - and these methodes are not exposed public in Cuba7 anyway.
Please advice...

Thanks
Steven

**Comment by smkdm** [comment]
Hi Matthias,

test fixed - thanks to Mario for his path

Please merge... 

Thanks
Steven

**Comment by bresche** [comment]
Thank you and Mario! 
I will merge it. 
Regards

**Comment by smkdm** [comment]
Hi Matthias,

what is the next steps to bring binary of the new version into the cuba repository?

I also working on the mgiration to Cuba 7.0 now and hope you will also address that when finished?

Thanks
Steven

**Pull request closed without merging**
